services:
  postgres:
    image: postgres:16-alpine
    container_name: voting_postgres
    environment:
      POSTGRES_DB: voting_db
      POSTGRES_USER: voting_user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U voting_user -d voting_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: voting_app
    ports:
      - "9090:9090"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: