spring.application.name=voting
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

logging.level.root=INFO
logging.level.com.univer.voting=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.file.name=logs/voting-system.log
logging.file.max-size=10MB
logging.file.max-history=30

voting.self-registration-enabled=true
voting.require-email-verification=true
voting.max-concurrent-elections=10
voting.site-title=Secure Online Voting System
voting.support-email=support@votingsystem.uz

voting.max-failed-login-attempts=5

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}

server.servlet.session.timeout=30m

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


voting.email.from=${MAIL_FROM}
voting.email.from-name=Voting System
spring.thymeleaf.cache=false
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

spring.banner.location=classpath:banner.txt

logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.mail.javamail=DEBUG
logging.level.javax.mail=DEBUG
logging.level.com.sun.mail=DEBUG


admin.username=${$ADMIN_USERNAME}
admin.pass=${ADMIN_PASS}
admin.mail=${ADMIN_MAIL}
