package com.univer.voting.enums;

public enum AuditAction {
    LOGIN, LOGOUT, VOTE_CAST, ELECTION_CREATE, ELECTION_CLOSE,
    USER_REGISTER, ADMIN_ACTION, ELECTION_UPDATE, CANDIDATE_ADD,
    CANDIDATE_UPDATE, ACCOUNT_ACTIVATED, PASSWORD_RESET
}
