package com.univer.voting.enums;

public enum NotificationType {
    ELECTION_CREATED, ELECTION_STARTING, ELECTION_ENDING,
    ELECTION_CLOSED, RESULTS_PUBLISHED, VOTE_CONFIRMED,
    ACCOUNT_ACTIVATED, ELIGIBILITY_GRANTED, ELIGIBILITY_REVOKED,
    SYSTEM_ANNOUNCEMENT
}
